version: '3'
services:
  database:
    image: postgres:16
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: twitter-backend
    ports:
      - "54321:5432"
