services:
  postgresdb:
    image: postgres:16
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "54321:5432"
    volumes:
#      ./data - path to the folder on the host machine where the database data will be stored
#      /var/lib/postgresql/data - path to the folder in the container where the database data will be stored
        - ./data:/var/lib/postgresql/data
    networks:
      - "twitter-svc-network"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      timeout: 20s
      retries: 10
  twitter-svc:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: twitter-svc
    ports:
      - "4747:4747"
    depends_on:
      postgresdb:
        condition: service_healthy
    networks:
      - "twitter-svc-network"
networks:
  twitter-svc-network:
    driver: bridge
    external: false
